storage:
  path: ./test_storage
  database: ./test_db/test.db

api:
  port: "8081"
  key: "test-api-key-12345"
  mode: hybrid  # native, s3, or hybrid

s3:
  enabled: true
  port: "9001"
  access_key: "testuser"
  secret_key: "testpass"
  region: "us-east-1"